kind: DaemonSet
apiVersion: apps/v1 
metadata:
  name: ds1 
  namespace: default 
  #labels: # optional
spec:
  selector:
    matchLabels:
      app: log 
  template: 
    metadata:
      labels:
        app: log 
    spec: 
      restartPolicy: Always
      #initContainers:
      containers:
        - name: cont1 
          image: nginx 
          ports:
            - name: http 
              containerPort: 80 

